name: petnest_saas
description: "PetNest SaaS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image: ^4.1.7

  # 🔥 Google 登入
  google_sign_in: ^6.2.1

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true