// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcT3K_RRTLwcVlOaQIU1oLJTvNjvjDa0',
    appId: '1:38879325834:web:ae2e59521bfcb9cbd40773',
    messagingSenderId: '38879325834',
    projectId: 'petnest-saas',
    authDomain: 'petnest-saas.firebaseapp.com',
    storageBucket: 'petnest-saas.firebasestorage.app',
    measurementId: 'G-RN0TSJB10M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltzTE0lSopC8deKI1wqzY2M8urmvnCjo',
    appId: '1:38879325834:android:72bf7d2447f14b7bd40773',
    messagingSenderId: '38879325834',
    projectId: 'petnest-saas',
    storageBucket: 'petnest-saas.firebasestorage.app',
  );
}
